development:
  uri: "mysql://root:@localhost/datainsights_format_success"
production:
  uri: "mysql://datainsight:@localhost/datainsights_format_success"
test:
  uri: "mysql://datainsight:datainsight@localhost/datainsights_format_success_test"
